import "./globals.css";
import Navbar from "../components/Navbar/navbar";
import Footer from "../components/Footer/Footer";


export const metadata = {
  title: "Preqt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
